docs/api.rst
PasswordWidget and TimeInputWidget were missing, this PR adds them to docs/api.rst
=> Add PasswordWidget and TimeInputWidget to API doc

README.rst, contributing.md
- add contributing.md to point to readme for new issues and PRs
=> - update readme for clarity

CONTRIBUTORS.txt
I backdated it to my first commit...
=> sign contributors.txt

CONTRIBUTING.rst
I'm working with @mamalos on #365. These PR slightly improves the instructions for running functional tests, but further assistance is needed.
=> improve instructions for running functional tests

.travis.yml, CHANGES.txt, README.rst, deform/form.py, deform/widget.py, docs/components.rst, docs/conf.py, docs/glossary.rst, docs/i18n.rst, docs/index.rst, docs/serialization.rst, docs/validation.rst, setup.py, tox.ini
=> Drop py33, add py37 as allowed failure, fix broken links

.gitignore, .travis.yml, tox.ini
=> Change Python 3.7 to use stable version, 3.8-dev as allowed failure, in Travis

.travis.yml, deform/form.py, deform/templates/form.pt, deform/tests/test_form.py
=> [WIP] Add HTML5 attributes to buttons

docs/widget.rst
=> Fix simple typo: reqested -> requested

README.rst, docs/api.rst, docs/glossary.rst, tox.ini
This PR should resolve the docs build issues. See #397.
=> Fix travis issues

contributing.md, run-selenium-tests.bash
- Add new tox installation method
- Add coding style for isort
- Update examples to use variable
=> Use cleanup method to safely cleanup locales

CHANGES.txt, CONTRIBUTORS.txt, deform/field.py, deform/form.py, deform/static/scripts/deform.js, deform/templates/autocomplete_input.pt, deform/templates/checkbox.pt, deform/templates/checkbox_choice.pt, deform/templates/checked_input.pt, deform/templates/checked_password.pt, deform/templates/dateinput.pt, deform/templates/dateparts.pt, deform/templates/datetimeinput.pt, deform/templates/file_upload.pt, deform/templates/moneyinput.pt, deform/templates/password.pt, deform/templates/radio_choice.pt, deform/templates/richtext.pt, deform/templates/select.pt, deform/templates/select2.pt, deform/templates/textarea.pt, deform/templates/textinput.pt, deform/templates/timeinput.pt, deform/tests/test_field.py, deform/tests/test_form.py, deform/tests/test_functional.py, deform/widget.py, setup.py
An attempt to revive and merge the abandoned PR #268.
=> Form focus

deform/static/select2/select2.css, deform/static/select2/select2.js
(cherry picked from commit 7c5b198518c6180f8c404be958cd1f02d16ae053)
Missed in release [2.0.12](https://github.com/Pylons/deform/releases/tag/2.0.12)
=> Updated select2 to version 4.0.13

contributing.md
- Add command to remove webdriver from macOS quarantine.
- Bump geckodriver version.
=> Improve section for Chrome.

contributing.md, tox.ini
added docker-py dependency and passed environment variables in tox.ini that is going to be used in Deformdemo to start selenium container.
=> Add selenium firefox container

contributing.md
See https://github.com/Pylons/deform/issues/472#issuecomment-686390541
=> Add a new section, When to add or edit functional tests

deform/compat.py, deform/tests/test_widget.py, deform/widget.py
=> Convert choices that are a generator to a list

deform/templates/dateparts.pt
- Adjust test to submit only numbers, but still be an invalid date (2020-02-31)
- Fixes #442
=> Change dateparts widget to use type=number

CHANGES.txt, deform/tests/test_widget.py, deform/widget.py
=> conditionally load jquery.maskedinput iff ``mask``

CHANGES.txt
(Note: I'm doing this prematurely to test the migration to travis-ci.com from .org.)
=> Add changelog entry

.github/workflows/ci-tests.yml, contributing.md, setup.py
Align port numbers. 8523 on main branch, 8522 on 2.0-branch
=> Fix GitHub Actions build failure

deform/field.py, setup.py
Pin selenium >= 4.0.0.b4 which fixes a regression with file upload functional tests
=> Pin selenium min 4.0.0.b4
